export { default as home } from "./home.png";
export { default as list } from "./list.png";
export { default as enlist } from "./enlist.png";
export { default as accept } from "./accept.png";
export { default as bike } from "./bike.png";
export { default as box } from "./box.png";
export { default as logo } from "./logo.png";
export { default as login } from "./login.png";
export { default as checkmark } from "./checkmark.png";
export { default as arrow } from "./arrow.png";
export { default as download } from "./download.png";
export { default as del } from "./delete.png"
export { default as developers } from "./developers.png"